# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }} ğŸ
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Installing yarn ğŸ”§
      run: |
        npm i -g yarn

    - name: Bootstraping project build ğŸ”§
      run: |
        cd js || exit
        yarn
        yarn bootstrap

    - name: Preparing commons ğŸ”§
      run: |
        cd js/packages/common || exit
        yarn prepare

    - name: Prestarting web ğŸ”§
      run: |
        cd js/packages/web || exit
        yarn prestart
        CI=false && yarn build
        yarn export


    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: js/build/web # The folder the action should deploy.
      
    # - name: Post Corrections ğŸ’‰
    #   run: |
    #     sed -i 's_="/_="./_g' ./index.html
